title = "Mecerka security config"

[extend]
useDefault = true

[allowlist]
description = "Ignore tests and dependencies"

paths = [
  '''node_modules''',
  '''dist''',
  '''coverage''',
  '''.*\.spec\.ts''',
  '''.*\.test\.ts'''
]

regexes = [
  '''mock_secret''',
  '''test_secret''',
  '''dummy_secret'''
]

