services:
  postgres:
    image: postgres:15-alpine
    restart: unless-stopped
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - mecerka_network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER}" ]
      interval: 5s
      timeout: 5s
      retries: 5
    # We do NOT publish ports to the EC2 host to keep DB closed from public internet
    # Internally accessible via the mecerka_network on 5432

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
    command: sh -c "npx prisma generate && npx prisma migrate deploy && node dist/src/main"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_SECRET_CURRENT=${JWT_SECRET_CURRENT}
      - CORS_ORIGIN=${CORS_ORIGIN}
      - FRONTEND_URL=${FRONTEND_URL}
      - STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}
      - STRIPE_WEBHOOK_SECRET=${STRIPE_WEBHOOK_SECRET}
      - DELIVERY_STRIPE_WEBHOOK_SECRET=${DELIVERY_STRIPE_WEBHOOK_SECRET}
      - DONATIONS_STRIPE_WEBHOOK_SECRET=${DONATIONS_STRIPE_WEBHOOK_SECRET}
      - MAIL_HOST=${MAIL_HOST}
      - MAIL_PORT=${MAIL_PORT}
      - MAIL_USER=${MAIL_USER}
      - MAIL_PASS=${MAIL_PASS}
      - MAIL_FROM=${MAIL_FROM}
      - BACKEND_URL=${BACKEND_URL}
      - PORT=3000
      - NODE_ENV=production
      - DEMO_MODE=${DEMO_MODE}
    ports:
      - "127.0.0.1:3000:3000" # Expose only to localhost for Nginx reverse proxy
    networks:
      - mecerka_network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
        NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY: ${NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY}
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
      - NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY=${NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY}
      - PORT=3001
      - HOSTNAME=0.0.0.0
    ports:
      - "127.0.0.1:3001:3001" # Expose only to localhost for Nginx reverse proxy
    networks:
      - mecerka_network

volumes:
  postgres_data:
    name: mecerka_postgres_volume

networks:
  mecerka_network:
    name: mecerka_network
    driver: bridge
