ALTER TABLE "City"
ADD COLUMN "baseDeliveryFee" DECIMAL(10, 2) NOT NULL DEFAULT 3.50,
ADD COLUMN "deliveryPerKmFee" DECIMAL(10, 2) NOT NULL DEFAULT 0.90,
ADD COLUMN "extraPickupFee" DECIMAL(10, 2) NOT NULL DEFAULT 1.50;

ALTER TABLE "Order"
ADD COLUMN "runnerExtraPickupFee" DECIMAL(10, 2);
